# image will be published to ghcr.io/<user>/<name>
name: ec-silverblue-nvidia-20240425
# description will be included in the image's metadata
description: This is my personal Silverblue Nvidia image from 20240425

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-nvidia
# base-image: ghcr.io/ublue-os/sericea-nvidia
# base-image: ghcr.io/ublue-os/kinoite-nvidia
base-image: ghcr.io/ublue-os/aurora-nvidia
# base-image: ghcr.io/wayblueorg/sway-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/alternateved/bleeding-emacs/repo/fedora-%OS_VERSION%/alternateved-bleeding-emacs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/nushell/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/g/sway-sig/sway-desktop/repo/fedora-%OS_VERSION%/group_sway-sig-sway-desktop-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/nucleo/gocryptfs/repo/fedora-%OS_VERSION%/nucleo-gocryptfs-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/pesader/gocryptfs/repo/fedora-%OS_VERSION%/pesader-gocryptfs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/alebastr/swayr/repo/fedora-%OS_VERSION%/alebastr-swayr-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/frostyx/qtile/repo/fedora-%OS_VERSION%/frostyx-qtile-fedora-%OS_VERSION%.repo
      # using a version without gpg-key control to test if it works
      # - https://gist.githubusercontent.com/ecocode/f910ca1621ba29220074bc281e6b8a78/raw/78f9178d29b8b051dcff5b95d305062a83c2c9eb/insync.repo
      - https://gist.github.com/ecocode/21beb822a05373ac063cb3bf1a550d6c/raw/a7ed5b79ef8d675bdd7e7866cf64fdfb67e27d74/terra.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      ## - https://copr.fedorainfracloud.org/coprs/flekz/helix-git/repo/fedora-%OS_VERSION%/flekz-helix-git-fedora-%OS_VERSION%.repo
      # - https://fbreader.org/linux/rpms/fbreader.repo
      # - https://terra.fyralabs.com/terra.repo
      # - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

    install:
      - atool
      - akregator
      - alot
      # - appimagelauncher
      - bat
      - bemenu
      # - bettercap
      - blueman
      - cargo
      - cryfs
      - cosmic-desktop
      - digikam
      - distrobox
      - dconf-editor
      - dolphin
      - egl-wayland
      - entr
      # epiphany is the package name of gnome web
      # - epiphany
      - eww
      - eza
      - fastfetch
      - fbreader
      - fd-find
      - firewall-config
      - fish
      - foot
      - foot-terminfo
      - fzf
      - gh
      - glances
      - glibc-locale-source
      - gnome-tweaks
      - gocryptfs
      - grim
      - gparted
      - gtk3
      - gvfs-gphoto2
      - gvfs-afc
      - hotspot
      - imv
      # - insync
      # - intel-media-driver
      - inxi
      - j4-dmenu-desktop
      - jrnl
      - kalendar
      - kamera
      - kf5-solid
      - kf6-solid
      - kio-gdrive
      - kio-extras-kf5
      - kio-fuse
      - kio-ftps
      - kjournald
      - kontact
      - ksystemlog
      - kwallet-pam
      - kanshi
      - kitty
      - kitty-terminfo
      - libimobiledevice
      - libimobiledevice-utils
      - libusb
      - light
      - lm_sensors
      - lshw
      - lynx
      - macchanger
      - mako
      - mediainfo
      - miracle-wm
      - mpv
      - neochat
      - neovim
      - network-manager-applet
      - NetworkManager-tui
      # - niri
      # - nnn
      - nushell
      # - nvidia-vaapi-driver
      - nvtop
      - odt2txt
      # - openh264
      - openssl-devel
      - pasystray
      - perf
      - perl-File-MimeInfo
      - plasma-wayland-protocols
      - pulseaudio-utils
      # - qutebrowser
      # - qt5-qtwebengine-freeworld
      - qt6-qtwayland
      # - qtile
      - ripgrep
      - river
      - rofi-wayland
      - samba
      # - sddm
      # - sddm-wayland-sway
      # - sddm-wayland-generic
      - slurp
      - sshfs
      - starship
      - strace
      # - sway
      - swaybg
      - swayr
      - swayidle
      - swaylock
      - sway-systemd
      - systemd
      - taskopen
      - tilix
      - tlp
      - tmux
      - trash-cli
      - usbip
      - udiskie
      - variety
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - w3m
      - waybar
      # - wayfire
      - webkit2gtk3
      - webkit2gtk4.0
      - wdisplays
      - wezterm
      - wl-clipboard
      - wofi
      - xdg-desktop-portal-wlr
      # - xorg-x11-drv-nvidia-cuda
      - zellij
      - zoxide

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency

      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.kde.krita
        - com.brave.Browser
        # - com.discordapp.Discord
        # - one.ablaze.floorp  # //lightning - This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog
    ## user:
    ##   repo-url: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
    ##   repo-name: 1Password
    ##   install:
    ##   - com.onepassword.OnePassword

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - Iosevka
        - Noto
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Noto Sans

  - type: script
    snippets:
    scripts:
      # - insync.sh
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
