# image will be published to ghcr.io/<user>/<name>
name: ec-silverblue-nvidia-20240425
# description will be included in the image's metadata
description: This is my personal Silverblue Nvidia image from 20240425

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/alternateved/bleeding-emacs/repo/fedora-%OS_VERSION%/alternateved-bleeding-emacs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/g/sway-sig/sway-desktop/repo/fedora-%OS_VERSION%/group_sway-sig-sway-desktop-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/nucleo/gocryptfs/repo/fedora-%OS_VERSION%/nucleo-gocryptfs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/alebastr/swayr/repo/fedora-%OS_VERSION%/alebastr-swayr-fedora-%OS_VERSION%.repo
      # - https://terra.fyralabs.com/terra.repo
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo

      ## - https://copr.fedorainfracloud.org/coprs/flekz/helix-git/repo/fedora-%OS_VERSION%/flekz-helix-git-fedora-%OS_VERSION%.repo
      - https://gist.github.com/ecocode/f910ca1621ba29220074bc281e6b8a78/raw/daa76873e8a38e16b0575b9c8099324667cb7dcf/insync.repo
      # - https://fbreader.org/linux/rpms/fbreader.repo

    install:
      - atool
      - alot
      # - appimagelauncher
      - bat
      - bemenu
      # - bettercap
      - blueman
      - cargo
      - cryfs
      - distrobox
      - dconf-editor
      - egl-wayland
      - entr
      # epiphany is the package name of gnome web
      # - epiphany
      - eza
      - fbreader
      - fd-find
      - firewall-config
      - fish
      - foot
      - foot-terminfo
      - fzf
      - glances
      - glibc-locale-source
      - gnome-tweaks
      # - gocryptfs
      - golang-github-rfjakob-gocryptfs
      - grim
      - gparted
      - hotspot
      - imv
      - insync
      - intel-media-driver
      - inxi
      - j4-dmenu-desktop
      - jrnl
      - kanshi
      - kitty
      - kitty-terminfo
      - light
      - lm_sensors
      - lshw
      - lynx
      - macchanger
      - mako
      - mediainfo
      - mpv
      - neovim
      - network-manager-applet
      - NetworkManager-tui
      - nnn
      - nushell
      # - nvidia-vaapi-driver
      - nvtop
      - odt2txt
      # - openh264
      - openssl-devel
      - pasystray
      - perf
      - perl-File-MimeInfo
      - plasma-wayland-protocols
      - pulseaudio-utils
      - qt6-qtwayland
      - ripgrep
      - river
      - rofi-wayland
      - samba
      - slurp
      - sshfs
      - starship
      - strace
      - sway
      - swaybg
      - swayr
      - swayidle
      - swaylock
      - taskopen
      - tilix
      - tmux
      - trash-cli
      - usbip
      - variety
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - w3m
      - waybar
      # - wayfire
      - webkit2gtk4.0
      - wdisplays
      - wezterm
      - wl-clipboard
      - wofi
      - xdg-desktop-portal-wlr
      - xorg-x11-drv-nvidia-cuda
      - zellij

    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.kde.krita
        - com.brave.Browser
        - com.discordapp.Discord
        - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).

        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),

      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        # - org.gnome.eog
    user:
      repo-url: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
      repo-name: 1Password
      install:
      - com.onepassword.OnePassword

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
